// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjetoVet.Data;

#nullable disable

namespace ProjetoVet.Migrations
{
    [DbContext(typeof(VetContext))]
    partial class VetContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProjetoVet.Models.Animal", b =>
                {
                    b.Property<int>("AnimalID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AnimalID"));

                    b.Property<DateTime?>("DataNascimento")
                        .HasColumnType("datetime2");

                    b.Property<int>("EspecieID")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("RacaID")
                        .HasColumnType("int");

                    b.Property<string>("Sexo")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("TutorID")
                        .HasColumnType("int");

                    b.HasKey("AnimalID");

                    b.HasIndex("EspecieID");

                    b.HasIndex("RacaID");

                    b.HasIndex("TutorID");

                    b.ToTable("Animais");
                });

            modelBuilder.Entity("ProjetoVet.Models.Endereco", b =>
                {
                    b.Property<int>("EnderecoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EnderecoID"));

                    b.Property<string>("Bairro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CEP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cidade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Logradouro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Numero")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TutorID")
                        .HasColumnType("int");

                    b.Property<string>("UF")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EnderecoID");

                    b.HasIndex("TutorID");

                    b.ToTable("Enderecos");
                });

            modelBuilder.Entity("ProjetoVet.Models.Especie", b =>
                {
                    b.Property<int>("EspecieID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EspecieID"));

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EspecieID");

                    b.ToTable("Especies");
                });

            modelBuilder.Entity("ProjetoVet.Models.Pessoa", b =>
                {
                    b.Property<int>("PessoaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PessoaID"));

                    b.Property<string>("CPF")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoPessoa")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.HasKey("PessoaID");

                    b.ToTable("Pessoas");

                    b.HasDiscriminator<string>("TipoPessoa").HasValue("Pessoa");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("ProjetoVet.Models.Raca", b =>
                {
                    b.Property<int>("RacaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RacaID"));

                    b.Property<int>("EspecieID")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RacaID");

                    b.HasIndex("EspecieID");

                    b.ToTable("Racas");
                });

            modelBuilder.Entity("ProjetoVet.Models.Funcionario", b =>
                {
                    b.HasBaseType("ProjetoVet.Models.Pessoa");

                    b.Property<string>("Cargo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataAdmissao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Login")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Salario")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Senha")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Funcionario");
                });

            modelBuilder.Entity("ProjetoVet.Models.Tutor", b =>
                {
                    b.HasBaseType("ProjetoVet.Models.Pessoa");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Tutor");
                });

            modelBuilder.Entity("ProjetoVet.Models.Veterinario", b =>
                {
                    b.HasBaseType("ProjetoVet.Models.Pessoa");

                    b.Property<string>("CRMV")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataAdmissao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataDemissao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Especialidade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Salario")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Situacao")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Pessoas", t =>
                        {
                            t.Property("DataAdmissao")
                                .HasColumnName("Veterinario_DataAdmissao");

                            t.Property("Salario")
                                .HasColumnName("Veterinario_Salario");
                        });

                    b.HasDiscriminator().HasValue("Veterinario");
                });

            modelBuilder.Entity("ProjetoVet.Models.Animal", b =>
                {
                    b.HasOne("ProjetoVet.Models.Especie", "Especie")
                        .WithMany("Animais")
                        .HasForeignKey("EspecieID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProjetoVet.Models.Raca", "Raca")
                        .WithMany("Animais")
                        .HasForeignKey("RacaID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProjetoVet.Models.Tutor", "Tutor")
                        .WithMany("Animais")
                        .HasForeignKey("TutorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Especie");

                    b.Navigation("Raca");

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("ProjetoVet.Models.Endereco", b =>
                {
                    b.HasOne("ProjetoVet.Models.Tutor", "Tutor")
                        .WithMany("Enderecos")
                        .HasForeignKey("TutorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("ProjetoVet.Models.Raca", b =>
                {
                    b.HasOne("ProjetoVet.Models.Especie", "Especie")
                        .WithMany("Racas")
                        .HasForeignKey("EspecieID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Especie");
                });

            modelBuilder.Entity("ProjetoVet.Models.Especie", b =>
                {
                    b.Navigation("Animais");

                    b.Navigation("Racas");
                });

            modelBuilder.Entity("ProjetoVet.Models.Raca", b =>
                {
                    b.Navigation("Animais");
                });

            modelBuilder.Entity("ProjetoVet.Models.Tutor", b =>
                {
                    b.Navigation("Animais");

                    b.Navigation("Enderecos");
                });
#pragma warning restore 612, 618
        }
    }
}
